# Word2vec configurations

WORD2VEC_PATH: "/inputs/data/word2vec/GoogleNews-vectors-negative300.bin"
EMBED_DIM: 300
GRAPH_OUTPUT_PATH: "/outputs/data/figures/"
TDIDF_OUTPUT_PATH: "/outputs/data/tf_idf/"
